config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, :home_town, presence: :true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  validates :title, :genre, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    order = params.fetch('order', 'name')
    home_town = params['home_town']
    @authors = Author.where('home_town LIKE ?', "%#{home_town}%")
    @authors = @authors.where("name ILIKE ?", "%#{params[:q]}%").order(order)
    @home_towns = Author.all.pluck(:home_town).uniq
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :home_town)
    end
end

app/controllers/books_controller.rb
require 'byebug'

class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    order = params.fetch('order', 'title')
    genre = params['genre']
    @books = Book.where('genre LIKE ?', "%#{genre}%")
    @books = @books.where("title ILIKE ?", "%#{params[:q]}%").order(order)
    set_genres
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new

    set_authors
    set_genres
  end

  # GET /books/1/edit
  def edit
    set_authors
    set_genres
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    def set_authors
      @authors = Author.all.map { |author| [author.name, author.id] }
    end

    def set_genres
      @genres = Book.pluck(:genre).uniq
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :genre, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def results_are_descending?
    params['order'] =~ /DESC$/
  end

  def get_existing(item)
    item.nil? ? nil : item.id
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :home_town %>
    <%= f.text_field :home_town %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<% params = request.query_parameters %>
<h1>Authors</h1>

<%= form_tag(authors_path, id: 'search', method: 'get', enforce_utf8: false) do %>
  <%= label_tag(:q, "Search authors:") %>
  <%= text_field_tag(:q) %>
  <%= hidden_field_tag :order, value = params[:order]%>
  <%= hidden_field_tag :home_town, value = params[:home_town]%>
  <%= submit_tag("Search", name: nil) %>
<% end %>

<%= form_tag authors_path, method: 'get', enforce_utf8: false do %>
  <%= select_tag 'home_town', options_for_select(@home_towns.each),
        onchange: 'this.form.submit()', prompt: 'Filter by home town' %>

  <%= hidden_field_tag :order, value = params[:order]%>
  <%= hidden_field_tag :q, value = params[:q]%>
<% end %>

<%= form_tag authors_path, method: 'get', enforce_utf8: false do %>
  <%= button_tag 'Reset filters', name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <% if results_are_descending? %>
        <th><%= link_to 'Name', authors_path(params.merge(order: 'name')) %></th>
      <% else %>
        <th><%= link_to 'Name', authors_path(params.merge(order: 'name DESC')) %></th>
      <% end %>
      <th>Home town</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.home_town %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %> <br />
<%= link_to 'Switch to books view', books_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Home town:</strong>
  <%= @author.home_town %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :genre %>
    <%= f.select :genre, options_for_select(@genres, selected: f.object.genre) %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.select :author_id, options_for_select(@authors, selected: get_existing(f.object.author)) %>
    <!-- <% if f.object.author.nil? %>
      <%= f.text_field :author %>
    <% else %>
      <%= f.text_field :author, value: f.object.author.name %>
    <% end %> -->
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<% params = request.query_parameters %>
<h1>Books</h1>

<%= form_tag(books_path, id: 'search', method: 'get', enforce_utf8: false) do %>
  <%= label_tag(:q, "Search book titles:") %>
  <%= text_field_tag(:q) %>
  <%= hidden_field_tag :order, value = params[:order]%>
  <%= hidden_field_tag :genre, value = params[:genre]%>
  <%= submit_tag("Search", name: nil) %>
<% end %>

<%= form_tag books_path, method: 'get', enforce_utf8: false do %>
  <%= select_tag 'genre', options_for_select(@genres.each), onchange: 'this.form.submit()', prompt: 'Filter by genre' %>
  <%= hidden_field_tag :order, value = params[:order]%>
  <%= hidden_field_tag :q, value = params[:q]%>
<% end %>

<%= form_tag books_path, method: 'get', enforce_utf8: false do %>
  <%= button_tag 'Reset filters', name: nil %>
<% end %>

<table>
  <thead>
    <tr>
      <% if results_are_descending? %>
        <th><%= link_to 'Title', books_path(params.merge(order: 'title')) %></th>
      <% else %>
        <th><%= link_to 'Title', books_path(params.merge(order: 'title DESC')) %></th>
      <% end %>
      <th>Genre</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.genre %></td>
        <td><%= book.author.name %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %> <br />
<%= link_to 'Switch to authors view', authors_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booknerd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>